// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/gal-Tab/reddit-cli/internal/cli"
	"github.com/gal-Tab/reddit-cli/internal/cliutil"
	"github.com/gal-Tab/reddit-cli/internal/client"
	"github.com/gal-Tab/reddit-cli/internal/config"
	"github.com/gal-Tab/reddit-cli/internal/mcp/cobratree"
	"github.com/gal-Tab/reddit-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("comment_get",
			mcplib.WithDescription("Look up a comment by its t1_ fullname. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Comment fullname (e.g. t1_xyz789)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/info.json", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("discover_subreddit_search",
			mcplib.WithDescription("Search for subreddits by name or description. Required: q. Optional: limit, sort."),
			mcplib.WithString("q", mcplib.Required(), mcplib.Description("Query string")),
			mcplib.WithString("limit", mcplib.Description("Max results (1-100)")),
			mcplib.WithString("sort", mcplib.Description("Sort: relevance, activity")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/subreddits/search.json", []mcpParamBinding{{PublicName: "q", WireName: "q", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"}, }, []string{"q", }),
	)
	s.AddTool(
		mcplib.NewTool("discover_subreddits",
			mcplib.WithDescription("Popular subreddits. Optional: limit, after."),
			mcplib.WithString("limit", mcplib.Description("Max subs (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/subreddits/popular.json", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("discover_subreddits_new",
			mcplib.WithDescription("Newly created subreddits. Optional: limit, after."),
			mcplib.WithString("limit", mcplib.Description("Max subs (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/subreddits/new.json", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("discover_users",
			mcplib.WithDescription("Popular users. Optional: limit."),
			mcplib.WithString("limit", mcplib.Description("Max users (1-100)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users/popular.json", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("frontpage_best",
			mcplib.WithDescription("Get the Reddit best listing. Optional: limit, after, before."),
			mcplib.WithString("limit", mcplib.Description("Max posts to return (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor: fullname of post to fetch after")),
			mcplib.WithString("before", mcplib.Description("Cursor: fullname of post to fetch before")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/best.json", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "before", WireName: "before", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("frontpage_get",
			mcplib.WithDescription("Get the Reddit frontpage (anonymous = best-of; cookie = personalized). Optional: limit, after, before (plus 1 more)."),
			mcplib.WithString("limit", mcplib.Description("Max posts to return (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor: fullname of post to fetch after")),
			mcplib.WithString("before", mcplib.Description("Cursor: fullname of post to fetch before")),
			mcplib.WithString("count", mcplib.Description("Number of items already seen")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/.json", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "before", WireName: "before", Location: "query"},{PublicName: "count", WireName: "count", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("live_get",
			mcplib.WithDescription("Live thread updates. Required: thread_id. Optional: limit."),
			mcplib.WithString("thread_id", mcplib.Required(), mcplib.Description("Live thread ID")),
			mcplib.WithString("limit", mcplib.Description("Max updates")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/live/{thread_id}.json", []mcpParamBinding{{PublicName: "thread_id", WireName: "thread_id", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{"thread_id", }),
	)
	s.AddTool(
		mcplib.NewTool("live_info",
			mcplib.WithDescription("Live thread metadata: title, description, state, viewer count. Required: thread_id."),
			mcplib.WithString("thread_id", mcplib.Required(), mcplib.Description("Live thread ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/live/{thread_id}/about.json", []mcpParamBinding{{PublicName: "thread_id", WireName: "thread_id", Location: "path"}, }, []string{"thread_id", }),
	)
	s.AddTool(
		mcplib.NewTool("me_downvoted",
			mcplib.WithDescription("Posts the user has downvoted (cookie mode only). Required: username. Optional: limit, after. (requires browser login)"),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Authenticated username")),
			mcplib.WithString("limit", mcplib.Description("Max items (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/downvoted.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("me_hidden",
			mcplib.WithDescription("Posts the user has hidden (cookie mode only). Required: username. Optional: limit, after. (requires browser login)"),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Authenticated username")),
			mcplib.WithString("limit", mcplib.Description("Max items (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/hidden.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("me_saved",
			mcplib.WithDescription("Posts and comments the user has saved (cookie mode only). Required: username. Optional: limit, after. (requires browser login)"),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Authenticated username (must match cookie owner)")),
			mcplib.WithString("limit", mcplib.Description("Max items (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/saved.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("me_subscriptions",
			mcplib.WithDescription("Subreddits the authenticated user is subscribed to (cookie mode only). Optional: limit, after. (requires browser login)"),
			mcplib.WithString("limit", mcplib.Description("Max subs (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/subreddits/mine/subscriber.json", []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("me_upvoted",
			mcplib.WithDescription("Posts the user has upvoted (cookie mode only). Required: username. Optional: limit, after. (requires browser login)"),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Authenticated username")),
			mcplib.WithString("limit", mcplib.Description("Max items (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/upvoted.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("multi_get",
			mcplib.WithDescription("Read a multireddit feed (combined listing across the multi's subs). Required: username, multiname. Optional: limit, sort, t."),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Multireddit owner's username")),
			mcplib.WithString("multiname", mcplib.Required(), mcplib.Description("Multireddit name")),
			mcplib.WithString("limit", mcplib.Description("Max posts (1-100)")),
			mcplib.WithString("sort", mcplib.Description("Sort: hot, new, top, rising, controversial")),
			mcplib.WithString("t", mcplib.Description("Timeframe (with sort=top|controversial)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/m/{multiname}.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "multiname", WireName: "multiname", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "t", WireName: "t", Location: "query"}, }, []string{"username","multiname", }),
	)
	s.AddTool(
		mcplib.NewTool("post_get",
			mcplib.WithDescription("Fetch a post and its full comment tree (flattened with depth+score in JSON output). Required: post_id. Optional: depth, limit, sort (plus 1 more)."),
			mcplib.WithString("post_id", mcplib.Required(), mcplib.Description("Post ID without the t3_ prefix (the alphanumeric segment from the URL)")),
			mcplib.WithString("depth", mcplib.Description("Max comment tree depth")),
			mcplib.WithString("limit", mcplib.Description("Max comments to return")),
			mcplib.WithString("sort", mcplib.Description("Comment sort: confidence, top, new, controversial, old, qa")),
			mcplib.WithString("comment", mcplib.Description("Focus on a specific comment ID and its descendants")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/comments/{post_id}.json", []mcpParamBinding{{PublicName: "post_id", WireName: "post_id", Location: "path"},{PublicName: "depth", WireName: "depth", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "comment", WireName: "comment", Location: "query"}, }, []string{"post_id", }),
	)
	s.AddTool(
		mcplib.NewTool("post_info",
			mcplib.WithDescription("Look up posts by ID(s) without their comment trees. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Comma-separated fullnames (e.g. t3_abc123,t3_def456)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/info.json", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("search_posts_get",
			mcplib.WithDescription("Search posts across all subreddits. Required: q. Optional: sort, t, type (plus 3 more)."),
			mcplib.WithString("q", mcplib.Required(), mcplib.Description("Query string (supports Reddit search operators: subreddit:, author:, title:, selftext:, NSFW:, self:, site:, url:)")),
			mcplib.WithString("sort", mcplib.Description("Sort: relevance, hot, top, new, comments")),
			mcplib.WithString("t", mcplib.Description("Timeframe: hour, day, week, month, year, all")),
			mcplib.WithString("type", mcplib.Description("Filter type: link (default), sr (subreddits), user")),
			mcplib.WithString("limit", mcplib.Description("Max results (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithString("include_over_18", mcplib.Description("Include NSFW results")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/search.json", []mcpParamBinding{{PublicName: "q", WireName: "q", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "t", WireName: "t", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "include_over_18", WireName: "include_over_18", Location: "query"}, }, []string{"q", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_controversial",
			mcplib.WithDescription("Controversial listing for a subreddit; --t selects timeframe. Required: subreddit. Optional: t, limit."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithString("t", mcplib.Description("Timeframe: hour, day, week, month, year, all")),
			mcplib.WithString("limit", mcplib.Description("Max posts (1-100)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/controversial.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "t", WireName: "t", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_hot",
			mcplib.WithDescription("Hot listing for a subreddit. Required: subreddit. Optional: limit, after, before (plus 1 more)."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix (e.g. golang)")),
			mcplib.WithString("limit", mcplib.Description("Max posts to return (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor: fullname of post to fetch after")),
			mcplib.WithString("before", mcplib.Description("Cursor")),
			mcplib.WithString("count", mcplib.Description("Items already seen")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/hot.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "before", WireName: "before", Location: "query"},{PublicName: "count", WireName: "count", Location: "query"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_info",
			mcplib.WithDescription("Subreddit metadata: subscribers, description, created, over_18, type. Required: subreddit."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/about.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_moderators",
			mcplib.WithDescription("Subreddit moderator list. Required: subreddit."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/about/moderators.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_new",
			mcplib.WithDescription("New listing for a subreddit. Required: subreddit. Optional: limit, after, before."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithString("limit", mcplib.Description("Max posts (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithString("before", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/new.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "before", WireName: "before", Location: "query"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_rising",
			mcplib.WithDescription("Rising listing for a subreddit (Reddit's own rising algorithm — see also `velocity`). Required: subreddit. Optional: limit."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithString("limit", mcplib.Description("Max posts (1-100)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/rising.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_rules",
			mcplib.WithDescription("Subreddit rules. Required: subreddit."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/about/rules.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_search",
			mcplib.WithDescription("Subreddit-scoped search. Required: subreddit, q. Optional: sort, t, restrict_sr (plus 2 more)."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithString("q", mcplib.Required(), mcplib.Description("Query string")),
			mcplib.WithString("sort", mcplib.Description("Sort: relevance, hot, top, new, comments")),
			mcplib.WithString("t", mcplib.Description("Timeframe: hour, day, week, month, year, all")),
			mcplib.WithString("restrict_sr", mcplib.Description("Restrict to this subreddit (default true for sub-scoped)")),
			mcplib.WithString("type", mcplib.Description("Filter type: link, sr, user")),
			mcplib.WithString("limit", mcplib.Description("Max results (1-100)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/search.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "q", WireName: "q", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "t", WireName: "t", Location: "query"},{PublicName: "restrict_sr", WireName: "restrict_sr", Location: "query"},{PublicName: "type", WireName: "type", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_top",
			mcplib.WithDescription("Top listing for a subreddit; --t selects timeframe. Required: subreddit. Optional: t, limit, after."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithString("t", mcplib.Description("Timeframe: hour, day, week, month, year, all")),
			mcplib.WithString("limit", mcplib.Description("Max posts (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/top.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "t", WireName: "t", Location: "query"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"}, }, []string{"subreddit", }),
	)
	s.AddTool(
		mcplib.NewTool("subreddit_wiki",
			mcplib.WithDescription("Read a wiki page from a subreddit. Required: subreddit, page."),
			mcplib.WithString("subreddit", mcplib.Required(), mcplib.Description("Subreddit name without the r/ prefix")),
			mcplib.WithString("page", mcplib.Required(), mcplib.Description("Wiki page slug (e.g. 'index', 'rules', 'faq')")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/r/{subreddit}/wiki/{page}.json", []mcpParamBinding{{PublicName: "subreddit", WireName: "subreddit", Location: "path"},{PublicName: "page", WireName: "page", Location: "path"}, }, []string{"subreddit","page", }),
	)
	s.AddTool(
		mcplib.NewTool("user_about",
			mcplib.WithDescription("User metadata: karma, account age, mod status, gold status. Required: username."),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Reddit username without the u/ prefix")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/about.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("user_comments",
			mcplib.WithDescription("Comments by this user. Required: username. Optional: limit, after, sort (plus 1 more)."),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Reddit username without the u/ prefix")),
			mcplib.WithString("limit", mcplib.Description("Max comments (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithString("sort", mcplib.Description("Sort")),
			mcplib.WithString("t", mcplib.Description("Timeframe")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/comments.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "t", WireName: "t", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("user_overview",
			mcplib.WithDescription("User overview: combined posts and comments in reverse-chrono. Required: username. Optional: limit, after, sort (plus 1 more)."),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Reddit username without the u/ prefix")),
			mcplib.WithString("limit", mcplib.Description("Max items (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithString("sort", mcplib.Description("Sort: hot, new, top, controversial")),
			mcplib.WithString("t", mcplib.Description("Timeframe (with sort=top|controversial)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/overview.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "t", WireName: "t", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("user_posts",
			mcplib.WithDescription("Posts submitted by this user. Required: username. Optional: limit, after, sort (plus 1 more)."),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Reddit username without the u/ prefix")),
			mcplib.WithString("limit", mcplib.Description("Max posts (1-100)")),
			mcplib.WithString("after", mcplib.Description("Cursor")),
			mcplib.WithString("sort", mcplib.Description("Sort: hot, new, top, controversial")),
			mcplib.WithString("t", mcplib.Description("Timeframe")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/submitted.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"},{PublicName: "limit", WireName: "limit", Location: "query"},{PublicName: "after", WireName: "after", Location: "query"},{PublicName: "sort", WireName: "sort", Location: "query"},{PublicName: "t", WireName: "t", Location: "query"}, }, []string{"username", }),
	)
	s.AddTool(
		mcplib.NewTool("user_trophies",
			mcplib.WithDescription("Trophies awarded to this user. Required: username."),
			mcplib.WithString("username", mcplib.Required(), mcplib.Description("Reddit username without the u/ prefix")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/user/{username}/trophies.json", []mcpParamBinding{{PublicName: "username", WireName: "username", Location: "path"}, }, []string{"username", }),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Run 'reddit-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API credentials." +
					"\n      Run 'reddit-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Run 'reddit-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "reddit-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "reddit-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "reddit",
		"description": "Read-only Reddit CLI with an offline SQLite mirror, FTS5 search, and velocity-tracking commands.",
		"archetype":   "content",
		"tool_count":  33,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion reddit-cli binary.",
		"auth": map[string]any{
			"type": "cookie",
		},
		"resources": []map[string]any{
			{
				"name": "comment",
				"description": "Comments by ID",
				"endpoints": []string{"get",  },
				"searchable": true,
			},
			{
				"name": "discover",
				"description": "Discover subreddits and users",
				"endpoints": []string{"subreddit_search", "subreddits", "subreddits_new", "users",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "frontpage",
				"description": "Reddit frontpage and best-of",
				"endpoints": []string{"best", "get",  },
				"searchable": true,
			},
			{
				"name": "live",
				"description": "Live threads",
				"endpoints": []string{"get", "info",  },
				"searchable": true,
			},
			{
				"name": "me",
				"description": "Authenticated reads (cookie mode only — run `auth login --chrome` first)",
				"endpoints": []string{"downvoted", "hidden", "saved", "subscriptions", "upvoted",  },
				"searchable": true,
			},
			{
				"name": "multi",
				"description": "Multireddit feeds",
				"endpoints": []string{"get",  },
				"searchable": true,
			},
			{
				"name": "post",
				"description": "Posts and their comment trees",
				"endpoints": []string{"get", "info",  },
				"searchable": true,
			},
			{
				"name": "search_posts",
				"description": "Site-wide post search across all of Reddit",
				"endpoints": []string{"get",  },
				"searchable": true,
			},
			{
				"name": "subreddit",
				"description": "Subreddit listings, metadata, rules, moderators, wiki, and scoped search",
				"endpoints": []string{"controversial", "hot", "info", "moderators", "new", "rising", "rules", "search", "top", "wiki",  },
				"searchable": true,
			},
			{
				"name": "user",
				"description": "User profile, activity, and trophies",
				"endpoints": []string{"about", "comments", "overview", "posts", "trophies",  },
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Velocity-ranked rising", "command": "velocity", "description": "Re-rank a subreddit's rising listing by upvotes-per-minute computed from local snapshot deltas, not by Reddit's own...", "rationale": "Requires periodic snapshots persisted locally; Reddit's API exposes only the current score, never the velocity.", "via": "mcp-command-mirror"},
			{"name": "Topic velocity across subs", "command": "pulse", "description": "Compare mentions-per-hour of a topic this window vs the prior window across N subreddits, surfacing which...", "rationale": "Requires FTS5 over both posts and comments joined to per-subreddit time-windowed counts. Reddit's search is...", "via": "mcp-command-mirror"},
			{"name": "Cross-sub topic sweep", "command": "sweep", "description": "Top posts mentioning a topic across N subreddits in a window, deduplicated via the local crosspost-edges table so...", "rationale": "Requires fan-out to N search.json calls plus a local crosspost-edges table to dedupe viral cascades — no single...", "via": "mcp-command-mirror"},
			{"name": "User activity rollup", "command": "user activity", "description": "All posts and comments by a user in a window, grouped by subreddit with karma sums, post counts, and first/last...", "rationale": "Requires walking the user's overview cursor and persisting locally so the GROUP BY can run; Reddit's UI shows a flat...", "via": "mcp-command-mirror"},
			{"name": "Crosspost cascade graph", "command": "cascade", "description": "Recursive walk of a post's crosspost graph rendered as a tree (or `--graph` DOT) showing every downstream crosspost...", "rationale": "Requires a local edges table plus on-demand expansion of unseen children. Reddit shows only one parent link in the UI.", "via": "mcp-command-mirror"},
			{"name": "Controversy-ratio finder", "command": "controversial-now", "description": "Posts in a subreddit window where comment-count divided by score is unusually high — the 'fight in the parking...", "rationale": "Requires per-post local snapshots so the ratio is computed against current values; Reddit's controversial sort is...", "via": "mcp-command-mirror"},
			{"name": "Watchlist with delta refresh", "command": "watchlist", "description": "A named bag of subreddits and users; one command refreshes them all and the diff sub-command reports what's new and...", "rationale": "Requires a local watchlist table tracking last-sync timestamps per entry; otherwise every check is a cold-start scrape.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Velocity-ranked rising", "insight": "Requires periodic snapshots persisted locally; Reddit's API exposes only the current score, never the velocity."},
			{"topic": "Topic velocity across subs", "insight": "Requires FTS5 over both posts and comments joined to per-subreddit time-windowed counts. Reddit's search is timeframe-coarse and single-sub."},
			{"topic": "Cross-sub topic sweep", "insight": "Requires fan-out to N search.json calls plus a local crosspost-edges table to dedupe viral cascades — no single API call returns this."},
			{"topic": "User activity rollup", "insight": "Requires walking the user's overview cursor and persisting locally so the GROUP BY can run; Reddit's UI shows a flat reverse-chrono feed."},
			{"topic": "Crosspost cascade graph", "insight": "Requires a local edges table plus on-demand expansion of unseen children. Reddit shows only one parent link in the UI."},
			{"topic": "Controversy-ratio finder", "insight": "Requires per-post local snapshots so the ratio is computed against current values; Reddit's controversial sort is across all time, not 'last 24h'."},
			{"topic": "Watchlist with delta refresh", "insight": "Requires a local watchlist table tracking last-sync timestamps per entry; otherwise every check is a cold-start scrape."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
