// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDiscoverCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "discover",
		Short: "Discover subreddits and users",
	}

	cmd.AddCommand(newDiscoverSubredditSearchCmd(flags))
	cmd.AddCommand(newDiscoverSubredditsCmd(flags))
	cmd.AddCommand(newDiscoverSubredditsNewCmd(flags))
	cmd.AddCommand(newDiscoverUsersCmd(flags))
	return cmd
}
