// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSearchPostsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagSort string
	var flagT string
	var flagType string
	var flagLimit int
	var flagAfter string
	var flagIncludeOver18 bool

	cmd := &cobra.Command{
		Use:   "search-posts <q>",
		Short: "Search posts across all subreddits",
		Long:  "Shortcut for 'search_posts get'. Search posts across all subreddits",
		Example: "  reddit-pp-cli search-posts example-value",
		Annotations: map[string]string{"pp:endpoint": "search_posts.get", "pp:method": "GET", "pp:path": "/search.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/search.json"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "q is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "q"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("q is required\nUsage: %s <%s>", cmd.CommandPath(), "q"))
			}
			params := map[string]string{}
			params["q"] = args[0]
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagT != "" {
				params["t"] = fmt.Sprintf("%v", flagT)
			}
			if flagType != "" {
				params["type"] = fmt.Sprintf("%v", flagType)
			}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			if flagAfter != "" {
				params["after"] = fmt.Sprintf("%v", flagAfter)
			}
			if flagIncludeOver18 != false {
				params["include_over_18"] = fmt.Sprintf("%v", flagIncludeOver18)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "search_posts", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort: relevance, hot, top, new, comments")
	cmd.Flags().StringVar(&flagT, "t", "", "Timeframe: hour, day, week, month, year, all")
	cmd.Flags().StringVar(&flagType, "type", "", "Filter type: link (default), sr (subreddits), user")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Max results (1-100)")
	cmd.Flags().StringVar(&flagAfter, "after", "", "Cursor")
	cmd.Flags().BoolVar(&flagIncludeOver18, "include-over-18", false, "Include NSFW results")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
