// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMultiPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagSort string
	var flagT string

	cmd := &cobra.Command{
		Use:   "multi <username> <multiname>",
		Short: "Read a multireddit feed (combined listing across the multi's subs)",
		Long:  "Shortcut for 'multi get'. Read a multireddit feed (combined listing across the multi's subs)",
		Example: "  reddit-pp-cli multi example-resource example-resource",
		Annotations: map[string]string{"pp:endpoint": "multi.get", "pp:method": "GET", "pp:path": "/user/{username}/m/{multiname}.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/user/{username}/m/{multiname}.json"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "username is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "username"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("username is required\nUsage: %s <%s>", cmd.CommandPath(), "username"))
			}
			path = replacePathParam(path, "username", args[0])
			if len(args) < 2 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "multiname is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "multiname"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("multiname is required\nUsage: %s <%s>", cmd.CommandPath(), "multiname"))
			}
			path = replacePathParam(path, "multiname", args[1])
			params := map[string]string{}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagT != "" {
				params["t"] = fmt.Sprintf("%v", flagT)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "multi", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Max posts (1-100)")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort: hot, new, top, rising, controversial")
	cmd.Flags().StringVar(&flagT, "t", "", "Timeframe (with sort=top|controversial)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
