// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSubredditSearchCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagSort string
	var flagT string
	var flagRestrictSr bool
	var flagType string
	var flagLimit int

	cmd := &cobra.Command{
		Use:   "search <subreddit>",
		Short: "Subreddit-scoped search",
		Example: "  reddit-cli subreddit search example-value --q example-value",
		Annotations: map[string]string{"pp:endpoint": "subreddit.search", "pp:method": "GET", "pp:path": "/r/{subreddit}/search.json", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("q") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "q")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/r/{subreddit}/search.json"
			path = replacePathParam(path, "subreddit", args[0])
			params := map[string]string{}
			if flagQ != "" {
				params["q"] = fmt.Sprintf("%v", flagQ)
			}
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagT != "" {
				params["t"] = fmt.Sprintf("%v", flagT)
			}
			if flagRestrictSr != false {
				params["restrict_sr"] = fmt.Sprintf("%v", flagRestrictSr)
			}
			if flagType != "" {
				params["type"] = fmt.Sprintf("%v", flagType)
			}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "subreddit", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Query string")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort: relevance, hot, top, new, comments")
	cmd.Flags().StringVar(&flagT, "t", "", "Timeframe: hour, day, week, month, year, all")
	cmd.Flags().BoolVar(&flagRestrictSr, "restrict-sr", false, "Restrict to this subreddit (default true for sub-scoped)")
	cmd.Flags().StringVar(&flagType, "type", "", "Filter type: link, sr, user")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Max results (1-100)")

	return cmd
}
