// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSubredditCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "subreddit",
		Short: "Subreddit listings, metadata, rules, moderators, wiki, and scoped search",
	}

	cmd.AddCommand(newSubredditControversialCmd(flags))
	cmd.AddCommand(newSubredditHotCmd(flags))
	cmd.AddCommand(newSubredditInfoCmd(flags))
	cmd.AddCommand(newSubredditModeratorsCmd(flags))
	cmd.AddCommand(newSubredditNewCmd(flags))
	cmd.AddCommand(newSubredditRisingCmd(flags))
	cmd.AddCommand(newSubredditRulesCmd(flags))
	cmd.AddCommand(newSubredditSearchCmd(flags))
	cmd.AddCommand(newSubredditTopCmd(flags))
	cmd.AddCommand(newSubredditWikiCmd(flags))
	return cmd
}
