// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUserCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "user",
		Short: "User profile, activity, and trophies",
	}

	cmd.AddCommand(newUserAboutCmd(flags))
	cmd.AddCommand(newUserCommentsCmd(flags))
	cmd.AddCommand(newUserOverviewCmd(flags))
	cmd.AddCommand(newUserPostsCmd(flags))
	cmd.AddCommand(newUserTrophiesCmd(flags))
	return cmd
}
